In [1]:
import numpy as np

In [2]:
dados = np.loadtxt(fname='inflammation.csv', delimiter=',')

In [3]:
dados  # The rows are the individual patients and the columns are there daily inflammation measurements.

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [4]:
dados.shape

(60, 40)

In [5]:
dados.mean(axis=0)  # Temperatura média por dia

array([  0.        ,   0.45      ,   1.11666667,   1.75      ,
         2.43333333,   3.15      ,   3.8       ,   3.88333333,
         5.23333333,   5.51666667,   5.95      ,   5.9       ,
         8.35      ,   7.73333333,   8.36666667,   9.5       ,
         9.58333333,  10.63333333,  11.56666667,  12.35      ,
        13.25      ,  11.96666667,  11.03333333,  10.16666667,
        10.        ,   8.66666667,   9.15      ,   7.25      ,
         7.33333333,   6.58333333,   6.06666667,   5.95      ,
         5.11666667,   3.6       ,   3.3       ,   3.56666667,
         2.48333333,   1.5       ,   1.13333333,   0.56666667])

In [6]:
dados.max(axis=1)  # Temperatura máxima

array([ 18.,  18.,  19.,  17.,  17.,  18.,  17.,  20.,  17.,  18.,  18.,
        18.,  17.,  16.,  17.,  18.,  19.,  19.,  17.,  19.,  19.,  16.,
        17.,  15.,  17.,  17.,  18.,  17.,  20.,  17.,  16.,  19.,  15.,
        15.,  19.,  17.,  16.,  17.,  19.,  16.,  18.,  19.,  16.,  19.,
        18.,  16.,  19.,  15.,  16.,  18.,  14.,  20.,  17.,  15.,  17.,
        16.,  17.,  19.,  18.,  18.])